"""CronHelper — manages crontab entries for school bell schedule."""

import logging
import subprocess
import tempfile

from src import config
from src.state import StateManager

logger = logging.getLogger(__name__)

# Base directory for the project (from centralized config)
PROJECT_DIR = str(config.PROJECT_DIR)

# Music base directory (from centralized config)
MUSIC_BASE = str(config.MUSIC_DIR)


def load_schedule() -> dict:
    """Load schedule from StateManager (carousel.json).

    Returns:
        Dict with schedule times, or default schedule if file missing/error.
    """
    state_manager = StateManager()
    return state_manager.get_schedule()


class CronHelper:
    """Manages crontab entries for bell schedule."""

    # Compatibilidad hacia atrás: BELL_TIMES como property
    @property
    def BELL_TIMES(self) -> dict:
        """Alias de compatibilidad hacia atrás para self.schedule."""
        return self.schedule

    def __init__(self):
        """Initialize CronHelper, loading schedule from JSON."""
        self.schedule = load_schedule()

    def generate_crontab(self) -> str:
        """Generate all crontab entries as string.

        Returns:
            String with 11 cron entries for the bell schedule.
            Each entry runs Monday-Friday (1-5), calls bell.py
            with the appropriate music type.
        """
        lines = []

        # Add header comments
        lines.append("# School Bell System - auto-generated by CronHelper")
        lines.append("# Runs Monday-Friday only (1-5)")
        lines.append("")

        # Generate entries for each music type
        for music_type, times in self.schedule.items():
            for time_str in times:
                # Parse time (format: "HH:MM")
                parts = time_str.split(":")
                minute = int(parts[1])
                hour = int(parts[0])

                # Cron format: minute hour day month weekday command
                # Weekday 1-5 = Monday-Friday
                cron_line = f"{minute} {hour} * * 1-5 /usr/bin/python3 {PROJECT_DIR}/bell.py {music_type}"

                lines.append(cron_line)

        # Add trailing newline
        lines.append("")

        return "\n".join(lines)

    def setup(self) -> None:
        """Add bell system entries to crontab (idempotent).

        Reads current crontab, checks if our entries already exist,
        and only adds them if they're not present.
        """
        # Clear existing crontab before adding new entries
        subprocess.run(["crontab", "-r"], check=False)

        try:
            # Read current crontab
            result = subprocess.run(
                ["crontab", "-l"],
                capture_output=True,
                text=True,
                timeout=5,
            )

            current_crontab = result.stdout if result.returncode == 0 else ""

            # Generate our entries
            new_entries = self.generate_crontab()

            # Check if our entries are already in crontab
            if "bell.py entrada" in current_crontab:
                logger.info("Crontab entries already exist, skipping setup")
                return

            # Append our entries
            if current_crontab and not current_crontab.endswith("\n"):
                current_crontab += "\n"

            updated_crontab = current_crontab + new_entries

            # Write to temp file and install
            import tempfile

            with tempfile.NamedTemporaryFile(mode="w", delete=False) as f:
                f.write(updated_crontab)
                temp_path = f.name

            subprocess.run(
                ["crontab", temp_path],
                check=True,
                timeout=5,
            )

            import os

            os.unlink(temp_path)

            logger.info("Crontab entries added successfully")

        except subprocess.TimeoutExpired:
            logger.error("Timeout while managing crontab")
        except subprocess.CalledProcessError as e:
            logger.error(f"Failed to update crontab: {e}")
        except Exception as e:
            logger.error(f"Error in crontab setup: {e}")

    def remove(self) -> None:
        """Remove our entries from crontab.

        Reads current crontab, filters out lines containing 'bell.py',
        and writes the filtered crontab back.
        """
        try:
            # Read current crontab
            result = subprocess.run(
                ["crontab", "-l"],
                capture_output=True,
                text=True,
                timeout=5,
            )

            if result.returncode != 0:
                logger.info("No crontab exists, nothing to remove")
                return

            current_crontab = result.stdout

            # Filter out our entries (lines containing 'bell.py')
            lines = current_crontab.split("\n")
            filtered_lines = [
                line for line in lines if "bell.py" not in line and "School Bell System" not in line
            ]

            updated_crontab = "\n".join(filtered_lines).strip()

            # Write back (empty string = remove crontab)
            import tempfile

            with tempfile.NamedTemporaryFile(mode="w", delete=False) as f:
                if updated_crontab:
                    f.write(updated_crontab + "\n")
                temp_path = f.name

            subprocess.run(
                ["crontab", temp_path],
                check=True,
                timeout=5,
            )

            import os

            os.unlink(temp_path)

            logger.info("Crontab entries removed successfully")

        except subprocess.TimeoutExpired:
            logger.error("Timeout while managing crontab")
        except subprocess.CalledProcessError as e:
            logger.error(f"Failed to update crontab: {e}")
        except Exception as e:
            logger.error(f"Error in crontab removal: {e}")
